version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'mongo_data:/data/db'

volumes:
  mongo_data:
    driver: local
